import type { ColumnType } from './supabase';

export const COLLEGE_COLUMNS: Array<{
  name: string;
  type: ColumnType;
  options?: string[];
  width?: number;
}> = [
  { name: 'College Name', type: 'text', width: 220 },
  { name: 'NIRF Rank', type: 'number', width: 110 },
  { name: 'Location', type: 'text', width: 160 },
  { name: 'Fees (LPA)', type: 'number', width: 120 },
  { name: 'Avg Package (LPA)', type: 'number', width: 150 },
  { name: 'Placement %', type: 'number', width: 130 },
  { name: 'Branches', type: 'tags', width: 200, options: ['CSE', 'ECE', 'ME', 'CE', 'EE', 'IT', 'AIDS', 'AIML'] },
  { name: 'Eligibility', type: 'text', width: 160 },
  { name: 'Status', type: 'dropdown', width: 130, options: ['Interested', 'Applied', 'Shortlisted', 'Rejected', 'Finalized'] },
  { name: 'Rating', type: 'rating', width: 110 },
  { name: 'Website', type: 'url', width: 180 },
  { name: 'Exam Accepted', type: 'tags', width: 200, options: ['JEE Main', 'JEE Advanced', 'GATE', 'CAT', 'BITSAT', 'State CET'] },
  { name: 'Favorite', type: 'checkbox', width: 100 },
  { name: 'Notes', type: 'text', width: 240 },
];

export const SAMPLE_COLLEGES = [
  {
    'College Name': 'IIT Bombay',
    'NIRF Rank': 3,
    'Location': 'Mumbai, Maharashtra',
    'Fees (LPA)': 2.2,
    'Avg Package (LPA)': 28,
    'Placement %': 95,
    'Branches': ['CSE', 'ECE', 'ME'],
    'Eligibility': 'JEE Advanced > 1000',
    'Status': 'Interested',
    'Rating': 5,
    'Website': 'https://www.iitb.ac.in',
    'Exam Accepted': ['JEE Advanced'],
    'Favorite': true,
    'Notes': 'Top tier, dream college',
  },
  {
    'College Name': 'IIT Delhi',
    'NIRF Rank': 2,
    'Location': 'New Delhi',
    'Fees (LPA)': 2.2,
    'Avg Package (LPA)': 30,
    'Placement %': 96,
    'Branches': ['CSE', 'ECE', 'EE'],
    'Eligibility': 'JEE Advanced > 500',
    'Status': 'Applied',
    'Rating': 5,
    'Website': 'https://home.iitd.ac.in',
    'Exam Accepted': ['JEE Advanced'],
    'Favorite': true,
    'Notes': '',
  },
  {
    'College Name': 'NIT Trichy',
    'NIRF Rank': 8,
    'Location': 'Tiruchirappalli, Tamil Nadu',
    'Fees (LPA)': 1.4,
    'Avg Package (LPA)': 14,
    'Placement %': 88,
    'Branches': ['CSE', 'ECE', 'ME', 'CE'],
    'Eligibility': 'JEE Main > 97 percentile',
    'Status': 'Interested',
    'Rating': 4,
    'Website': 'https://www.nitt.edu',
    'Exam Accepted': ['JEE Main'],
    'Favorite': false,
    'Notes': 'Good NIT, strong placement',
  },
  {
    'College Name': 'BITS Pilani',
    'NIRF Rank': 23,
    'Location': 'Pilani, Rajasthan',
    'Fees (LPA)': 5.5,
    'Avg Package (LPA)': 18,
    'Placement %': 90,
    'Branches': ['CSE', 'ECE', 'ME'],
    'Eligibility': 'BITSAT > 360',
    'Status': 'Applied',
    'Rating': 4,
    'Website': 'https://www.bits-pilani.ac.in',
    'Exam Accepted': ['BITSAT'],
    'Favorite': false,
    'Notes': 'High fees but great industry connections',
  },
  {
    'College Name': 'VIT Vellore',
    'NIRF Rank': 11,
    'Location': 'Vellore, Tamil Nadu',
    'Fees (LPA)': 3.5,
    'Avg Package (LPA)': 9,
    'Placement %': 85,
    'Branches': ['CSE', 'ECE', 'IT', 'AIDS', 'AIML'],
    'Eligibility': 'VITEEE',
    'Status': 'Shortlisted',
    'Rating': 3,
    'Website': 'https://vit.ac.in',
    'Exam Accepted': ['JEE Main', 'State CET'],
    'Favorite': false,
    'Notes': 'Good placements, large campus',
  },
];

export const STATUS_COLORS: Record<string, string> = {
  'Interested': 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300',
  'Applied': 'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300',
  'Shortlisted': 'bg-cyan-100 text-cyan-800 dark:bg-cyan-900/30 dark:text-cyan-300',
  'Rejected': 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300',
  'Finalized': 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300',
};
